### ISSUE TITLE
Eggs with specific world hatch conditions hang the server when theyre loaded.

### ISSUE THREAD

**Issue by dianamonde** [WolfShotz/Wyrmroost#103]
[crash-2020-10-10_21.30.15-server.txt](https://github.com/WolfShotz/Wyrmroost/files/5360085/crash-2020-10-10_21.30.15-server.txt)

**Comment by WolfShotz** [comment]
"Server Hanging" could literally be anything. Maybe it is wyrmroost, maybe it isn't. Theres needs to be solid evidence that this is wyrmroosts doing. Try removing it?

**Comment by LagoonTheAbyssal** [comment]
I'd also like to note the end of the crash log
`Data Packs: mod:theoneprobe (incompatible), mod:dustrial_decor, mod:berry_good (incompatible), mod:enhanced_mushrooms, mod:extraboats, vanilla, mod:wyrmroost (incompatible), mod:phosphor, mod:snailmail, mod:curiousshulkerboxes (incompatible), mod:jei (incompatible), mod:abnormals_core, mod:buzzierbees, mod:atmospheric, mod:caelus (incompatible), mod:upgrade_aquatic (incompatible), mod:bloomful (incompatible), mod:curios (incompatible), mod:toadterror (incompatible), mod:savageandravage, mod:patchouli (incompatible), mod:neat (incompatible), mod:waystones (incompatible), mod:journeymap (incompatible), mod:autumnity, mod:citadel (incompatible), mod:rats (incompatible), mod:autoreglib (incompatible), mod:worldofwonder, mod:unnamedanimalmod, mod:midnight, mod:curioofundying (incompatible), mod:endergetic (incompatible), mod:curiouselytra (incompatible), mod:bedspreads (incompatible), mod:backtools (incompatible), mod:ichunutil (incompatible), mod:swampexpansion (incompatible), mod:forge (incompatible), mod:quark, mod:wings (incompatible), mod:cosmeticarmorreworked (incompatible), mod:extendednether (incompatible), mod:rotten_creatures`
though I doubt it's this is an accurate tell given the crash, it's not really possible to tell what is causing this from this file. Grabbing a log file (if possible) instead of a crash file would likely help a lot more to figure out what's causing the issue.

**Comment by WolfShotz** [comment]
an incompatible datapack means nothing really

**Comment by WolfShotz** [comment]
Eggs that have conditions that need the world (getting blocks at a specific spot) will cause the server to hang. This is because the egg is trying to check conditions where the chunk hasn't even loaded yet.
