### ISSUE TITLE
Drakes hit you in the air after they flind you up.

### ISSUE THREAD

**Issue by TRCI101** [WolfShotz/Wyrmroost#18]
Drake: "Oh hey there, you trying to tame me?"

Me: "Yes, let me be your friend."

Drake: "No fuck you" *Proceeds to fling me in the air*

Drake: "You're in the air? Doesn't matter, I have to power to travel through space and hit you 20ft above me." *proceeds to hit me from a range that shouldn't be possible*

Me: *Takes damage from fling and dimensional travel. Then takes added fall damage*

**Comment by WolfShotz** [comment]
I was afraid of this. Reason for this is because I basically put scotch tape on a leaky pipe. I can't particularly do math the right way yet to be able to calculate its direction facing, building a bounding box forward in that direction, and then damaging all entities in that box.
I will be putting more effort into this for 1.2. For now, I apologize.

**Comment by WolfShotz** [comment]
Fixed in https://github.com/WolfShotz/Wyrmroost/commit/af1b3504f19f44f375416e667e4c1b9adc4e4bb7
and
https://github.com/WolfShotz/Wyrmroost/commit/4f3a1ce30a89f60e67a671d861612d47ba34c6eb
