### ISSUE TITLE
Dragons disappearing after having been released from crystal.

### ISSUE THREAD

**Issue by Midnytesun** [WolfShotz/Wyrmroost#188]
**Steps to Reproduce:**
 1. Place a dragon in a Dragon Soul Crystal.
 2. Release dragon from Dragon Soul Crystal.
 3. Mount dragon and fly around, it will disappear after a while.

After release and install of holiday patch went around exploring to see the new holiday skins and tame some.
Found one of those nether portal ruins down in a ravine. Put the RR I was riding in a crystal and went down and gathered items. Afterwards released dragon and flew off to continue looking for wild dragons. After a few minutes the RR just despawned, dropping my character to the ground. Went back to where it had been placed and released from a crystal and it was not there. Checked base and it was not there. Have had no issues using crystals before update.

While waiting for videos to upload to youtube I was able to replicate the bug using an alpine and another RR.

Playing single player, game did not crash so no game log.

MC Version 1.16.3

Video of finding portal ruin and putting RR in crystal, gathering weeping obsidian, releasing dragon and flying way.

https://youtu.be/6EjF9fo8XZU

I periodically stop and restart recording so the videos don't get too big and unplayable, I did such a break just before dragon poofed. Video of RR despawning.

https://youtu.be/epegPYrJiEU

**Comment by Daejangnamu** [comment]
Same problem. My Red royal has been despawned.

**Comment by WolfShotz** [comment]
Potential Cause:
Something related to "Vehicle Moved Wrongly".

**Comment by LilTankReforged** [comment]
Ive tamed 3 Alpines and they all despawned in mid air and i died literally 3 times wayyy far away from my spawn ._.

**Comment by WolfShotz** [comment]
If I can figure it out I'm definetly going to be releasing a patch for this..

**Comment by TerranE5** [comment]
I have the same problem recently. Whe you put the royal red in the end when releasing it from the soul crystal, they will disappear after a short while. The world is hardcore, and I have never been so glad that I've created a backup beforehand.

**Comment by DebonairDoug** [comment]
This same issue has been very prevalent on the modded server I'm hosting for my friends. Its happened to alpines and butterfly levis many times over the past few days. From the server logs I can see two possible causes for the bug. The first is an issue with the "vehicle" moving wrongly which usually occurs when the server is behind on ticks and is trying to catch up. The log says "Alpine Dragon (vehicle of [player's username]) moved too quickly". The second has to do with duplicate entities being loaded in different dimensions such as the nether and end (I think). The console will log "Trying to add entity with duplicated UUID" followed by the entity id. I can provide exact details of the console if necessary but I would rather not share it publicly just because I'm port forwarding the server and don't want to accidentally leak my ip or something.
