### ISSUE TITLE
Feature request: config options for platinum ore

### ISSUE THREAD

**Issue by Febilian** [WolfShotz/Wyrmroost#200]
I can't help but notice that platinum doesn't do anything beyond adding another set of tool materials to work with, and doesn't seem to do anything particularly involved with the dragons themselves?

Given this, it'd at least be nice to have a toggle config for whether the ore spawns or not. Maybe someone wants to use a different mod's platinum generation or configure how rare/where it spawns in a pack, for example.

**Comment by WolfShotz** [comment]
Yeah, all the ores and materials are planned to get re-balanced and re-designed. To help them better fit in to the mod.
Second of all, to combat mojangs shitty system I've made thoughts of making my own json loader in terms of world generation, since datapacks can't seem to modify mod features directly yet, which my system could solve.

Also, as for future note, please keep suggestions and requests in the discord (which can be found in the readme for this repo) I like to keep github issues SPECIFICALLY for bugs and issues, thx!
