### ISSUE TITLE
Unnamed Loot pool with coin dragon injection

### ISSUE THREAD

**Issue by vadosepanther** [WolfShotz/Wyrmroost#203]
Logs: n/a

Steps to Reproduce:
 1. install the latest versions of wyrmroost and ice and fire
 2. create new world
 3. load into world
 4. go into spectator and locate a mineshaft or use /locate
 5. find a chest and ensure that the loot hasn't been loaded (right click in spectator)
 6. chest will be empty when opened

Description of issue: pretty simple if you read the how to when both wyrmroost and ice and fire exist on/in the same world there are no crashes or anything but mineshaft chests don't spawn with loot i tested this with only wyrmroost installed and there was loot same when i only had ice and fire installed but when i had both at the same time nothing was in chest at all not even vanilla items. thank you for your time in reading this minor issue report

**Comment by WenXin20** [comment]
When this mod is run with other mods, it can cause empty loot chests because of the unnamed loot tables. This also happens when Minecolonies or Artifacts is installed, and probably other mods too. Enigmatic Legacy made this easier to identify by printing which mods are causing it.
[Error Log](https://gist.github.com/WenXin20/bdc3fe84060896b24a6dfedca91c5ef9#file-loot_table_error-log-L73)

**Comment by Extegral** [comment]
I see this is already fixed in yesterday's commit, so guess we'd just have to wait until next mod version is built and released.

**Comment by Yourname942** [comment]
I Also have this issue:
debug log: https://gist.github.com/Yourname942/24231aa7c55344ced91dfbb001a90b29

**Comment by WolfShotz** [comment]
Yes the issue has been resolved in dev, I will be leaving this issue open to prevent dupe issues and to tell people that I'm aware of it.
Thank you everyone for the patience!
