### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by iShadowyz** [WolfShotz/Wyrmroost#226]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

[2021-02-03-1.log](https://github.com/WolfShotz/Wyrmroost/files/5921676/2021-02-03-1.log)

[crash-2021-02-03_18.16.33-server.txt](https://github.com/WolfShotz/Wyrmroost/files/5921679/crash-2021-02-03_18.16.33-server.txt)

**Steps to Reproduce:**
 1. Breed two overworld dragons
 2. Reproduce them
 3. And... Crash

**Description of issue:**
I use the last version of Wyrmroost 1.2.11
Version minecraft: 1.16.4
Version Forge: 35.1.37

**Comment by LagoonTheAbyssal** [comment]
Wow, thanks, this will be patched asap... /s

If you have an issue actually attach crash report info or the bug you're having. Opening a blank issue named "Crash" helps literally no one.

**Comment by iShadowyz** [comment]
I edited

**Comment by WolfShotz** [comment]
This seems to be caused by a mod called `Pet Names`, and since I cannot check the source code for the problem (It's private) I have to go on the assumption that the dev is not covering a case where the bred animal could possibly be null. Which since Wyrmroost breeding is unique (Drops an egg instead of an actual living creature) that's what happens. The animal is null since it doesn't exist yet (has to hatch).
