### ISSUE TITLE
[Feature request] Config option to disable ores

### ISSUE THREAD

**Issue by mcquestion** [WolfShotz/Wyrmroost#233]
MC Version: 1.16.5

Really love this mod but having trouble disabling the oregen.

PS: Thanks a million for this mod! :)

**Comment by scottsumrall** [comment]
+1 on this. Awesome mod, would love to be able to tweak ore gen.

**Comment by MarioSMB** [comment]
Definitely agree here, diamond-tier gems spread commonly throughout the worlds seems out of place for an otherwise amazing dragon mod.

**Comment by WolfShotz** [comment]
For future reference, please do not submit feature requests on the github. I use this as the bug tracker to keep issues organized. You can join the discord to pledge these though!

As for configuration files regarding world gen, the problem is these things screw with data packs. You can't have two different things trying to change one thing, as it will result in only one taking the effect. So I am going to have to say no to that, sorry.
