### ISSUE TITLE
Royal Red takes dmg from other Red Royal depending on whether I ride it or not

### ISSUE THREAD

**Issue by BEARPOW3R** [WolfShotz/Wyrmroost#269]
During exploration on my female Royal Red I stumbled upon male Royal Red and it attacked me. During flight, only I took dmg/could be set on fire. I landed to test if fire on blocks could hurt my dragon and it couldn't (I was on its back). I got off the dragon, hoping to defeat the male. It ignored me and the two dragons engaged in a fire-breathing fight. In the end, my **tamed dragon was scorched to death** which took me off guard as it did not take any dmg previously.

(I don't know if this might be relevant, but I also experienced the "tamed RR still attacks me" bug an hour prior to the situation described, but resolved it by mounting the dragon on creative and turning to survival on the dragon).
I apologize if it was alreaddy issued!

**Comment by Therzis** [comment]
This is not an issue.

This happens because your RR is defending you. It's like a wolf: if a zombie attacks you, the wolf will try to kill it. The RR doesn't defend you while you are riding it because it prioritizing your "fly this way" command, as soon as you get off the dragon it'll defend you from the other dragon.

**Comment by WolfShotz** [comment]
Also fire breath has impact damage. It didn't take direct fire damage but it is labelled as such for other fire-related occurences (Cooked meat from cows)
All this is intentional behavior

**Comment by BEARPOW3R** [comment]
Thank you so much for answering so fast! Keep up great work!
