### ISSUE TITLE
Suggesting for better config file

### ISSUE THREAD

**Issue by demon112** [WolfShotz/Wyrmroost#289]
Please add a config file to change the dragons speed and health its frustrating that the leviathan is poo slow

**Comment by FelisGamerus** [comment]
Really? They're slow for you? Wait, are you in water or on land? A Butterfly Leviathan in water is quite fast, but on land it is very slow because what you've done is taken an animal that has evolved to spend most of its life in water and now you've put it way out of its habitat. It's quite like vanilla's sea turtle's, actually

**Comment by WolfShotz** [comment]
Please do not make suggestions on the issue page. It is for tracking bugs and problems with the mod. If you want to make quick suggestions on mod mechanics (not features, we're not looking for them) you can join the discord and tell us there.

As for changing stats, That is a complex scenario. Before I commit to making things customizable through configs I want to see how things fare out in datapacks.
