### ISSUE TITLE
Crash with summoning wyrmroost:dragon_egg

### ISSUE THREAD

**Issue by PixelEyeStudios** [WolfShotz/Wyrmroost#29]
https://pastebin.com/iE1huj24 I tried doing the command /summon NoxEternisC wyrmroost:dragon_egg and it crashed xD

**Comment by Kingdomall** [comment]
You probably shouldn't have. Creative & JEI menu has it available. Even then we recommend that you don't cheat in eggs in survival.
This isn't really an issue. You didn't specifically type the NBT, and you tried to obtain an egg in a strange fashion, when in fact you could have given yourself an egg with the correct NBT values, then place it down.
I believe there are commands for this. _/give NoxEternisC wyrmroost:drake_egg_ Or something similar.
This kind of issue is common when trying to summon something that requires the right values.
We can make a fail safe for this but next time give yourself the egg instead of the summon. Thanks.
