### ISSUE TITLE
Crash everytime i load my world

### ISSUE THREAD

**Issue by demon112** [WolfShotz/Wyrmroost#319]
So i sorta did /summon wyrmroost:alpine_dragon ~ ~ ~ {Owner:xyvgamer,Variant:6} i think it was exactly that and anyway the moment i did it the game crashed and i cant open it anymore i dont know what to do and rather not lose the entire world
[crash-2022-02-10_23.01.07-client.txt](https://github.com/Kay9Unit/Wyrmroost/files/8052588/crash-2022-02-10_23.01.07-client.txt)

**Comment by Therzis** [comment]
This bug happens when you try to spawn some Wyrmroost entities that don't exist. There are 6 alpine variants and their "numbers" go from 0 to 5, so when you spawn a 6 the game crashes because there isn't a 7th variant. This is why I always recommend trying this in a world that can be deleted because crashes and corruption may happen

I'm not sure if you can get that world back. Try making a backup and then reloging a 3 or 5 times with that backup, it may work (this worked for me with another crash that was caused by entities, but the crash was not related to Wyrmroost). If that doesn't work you could try using NBTExplorer, it let's you look at what's happening in your world and modify it without having to load into the world. Iirc you don't even need to open Minecraft to use it. Try looking at the folders there and see if you find something related to entities try deleting the alpine entity, this will probably save your world. Another option would be reloading the world with all your other mods except for Wyrmroost. This deletes everything Wyrmroost in your world but you *may* get your world back, although it doesn't always work (try all of this in a backup world just to be sure)

You can get a backup of your worlds by going to the options section of your world and hitting the backup button. Then you go to the backup folder inside the .minecraft folder and move the unzipped file into the saves folder inside .minecraft. You can do this even with the game open, you just need to go to the main menu and back to the singleplayer menu to see it

I hope this helps

**Comment by demon112** [comment]
Thank you! I was able to load the world with a backup! This was incredibly helpful. Thank you for taking the time to write this for me.

**Comment by Therzis** [comment]
Awesome! I'll recommend this solution more often
