### ISSUE TITLE
Purple Dragonfruit Drakes Not Aggroing

### ISSUE THREAD

**Issue by EveTFB** [WolfShotz/Wyrmroost#64]
I've noticed that the dragonfruit drakes with purple bellies don't act aggressive, I have walked amongst them and they don't even care a lick about me, where as the dragonfruit drakes with white bellies will aggro onto me from around five blocks away

**Comment by LagoonTheAbyssal** [comment]
+ Female dragonfruit drakes are supposed to be more aggressive iirc but the males should still be hostile as well.

**Comment by katubug** [comment]
All the Dragonfruit Drakes on my server are friendly. The only time one ever tried to attack me first was when I was fighting a skeleton nearby.

**Comment by katubug** [comment]
That said, I really love them being passive. A TON of them spawn in my vicinity and they're lovely to live with. Also it would be extremely frustrating for them to be aggressive, since they don't respect Torchmaster spawn blocking and there's an absolute BOATLOAD of them.

**Comment by LagoonTheAbyssal** [comment]
@katubug Dragonfruit drake overspawning will be fixed as of next release (hopefully). As such this will bring back their aggression.
For getting rid of untamed dragonfruit drakes you can try this command:
`kill @e[type=wyrmroost:dragonfruit_drake,nbt={OwnerUUID:""}]`
the type may not be correct but it's been a while since I've played with the mod :) I hope it helps with any lag issues you may encounter!
